//@isTest
public with sharing class AP001_OnLoanVehicleAPIClass_TEST {
    /*@isTest 
    static void testParse(){
        String json = '{\"onLoanVehicle\":[{\"registrationNumber\":\"7897NV15\",\"make\":\"Nissan\",\"model\":\"Hardbody x38\",\"YearOfVehicle\":\"2015\"}}'
        AP001_OnLoanVehicleAPIClass obj = AP001_OnLoanVehicleAPIClass.parse(json);
        System.assert(obj != null);
    }
    */
}
